global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['es-exporter:9114']
